require("prototypes.item.item-groups")
require("prototypes.item.item-accumulators")
require("prototypes.item.item-solar-panels")
require("prototypes.item.item-substations")
require("prototypes.item.item-power-poles")
require("prototypes.item.item-trains")
require("prototypes.item.item-transport")
require("prototypes.item.item-logistics")
require("prototypes.item.item-equipment")

require("prototypes.recipe.recipe-accumulators")
require("prototypes.recipe.recipe-solar-panels")
require("prototypes.recipe.recipe-substations")
require("prototypes.recipe.recipe-power-poles")
require("prototypes.recipe.recipe-trains")
require("prototypes.recipe.recipe-transport")
require("prototypes.recipe.recipe-logistics")
require("prototypes.recipe.recipe-equipment")

require("prototypes.entity.entity-accumulators")
require("prototypes.entity.entity-solar-panels")
require("prototypes.entity.entity-substations")
require("prototypes.entity.entity-power-poles")
require("prototypes.entity.entity-trains")
require("prototypes.entity.entity-transport")
require("prototypes.entity.entity-logistics")
require("prototypes.entity.entity-equipment")

require("prototypes.technology.technology-electrical-engineer")
require("prototypes.technology.technology-transport-engineer")
require("prototypes.technology.technology-logistical-engineer")
require("prototypes.technology.technology-logistic-trash-slots")
require("prototypes.technology.technology-robot-speed")
require("prototypes.technology.technology-robot-storage")
require("prototypes.technology.technology-equipment")
